AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API to send SMS using SNS

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:  
      StageName: dev
      Auth:
        ApiKeyRequired: true
      DefinitionBody: # OpenApi standard
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './api.yaml'
      OpenApiVersion: 3.0.3
      EndpointConfiguration:
          Type: REGIONAL
       
  RoleForSNS:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: API-SNSSMS
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: SNS_SMS
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: [ "sns:Publish"]
                Resource: "*"
              - Effect: Deny
                Action: ["sns:Publish"]
                Resource: "arn:aws:sns:*:*"
                
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties: 
      ApiStages: 
        - ApiId: !Ref RestApi
          Stage: !Ref RestApi.Stage
      Description: Usage plan for this API
      Quota:
        Limit: 100
        Period: MONTH
      Throttle:
        BurstLimit: 10
        RateLimit: 10
      Tags:
        - Key: usage-plan
          Value: micro-apigw-sns-sms
  
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties: 
      Enabled: True

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  Deployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestApi

Outputs:
  API:
    Description: API to send SMS using SNS
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/dev"